In [4]:
# para importar

import numpy as np

In [6]:
# Neste exemplo, vamos usar o NumPy para criar uma matriz. Eu não vou dar as dimensões da matriz e outras informações, 
# já que vamos usar os atributos acima.

my_array = np.array(((1,3,4),
                    (5,3,2),
                    (7,9,1),
                    (9,5,1)))
print (my_array)

[[1 3 4]
 [5 3 2]
 [7 9 1]
 [9 5 1]]


In [7]:
# Para saber o tipo de dados da matriz podemos recorrer ao atributo dtype

print (my_array.dtype)

int32


In [8]:
# para saber o formato de um array temos o atributo shape. Ele retorna uma tupla contendo o formato do array

print (my_array.shape) #retorna uma tupla informando que o array possui 4 linhas e 3 colunas (4,3)

(4, 3)


In [9]:
# O atributo size retorna o número de elementos na matriz.

print (my_array.size)

12


In [10]:
# O atributo itemsize retorna o tamanho de um elemento da matriz em bytes.

print (my_array.itemsize)

4


In [11]:
# O atributo ndim retornará o número de dimensões da matriz
# Nesse caso retornará 2, significa que esta matriz consiste de duas dimensões.

print (my_array.ndim)

2


In [18]:
# para selecionar elementos na matriz podemos usar a seguinte sintaxe

print (my_array[0,2])

4


In [19]:
# selecionando apenas a primeira coluna

print (my_array[0,])

[1 3 4]


In [20]:
# criando uma matriz vazia não inicializada utilizando os atributos

empty_array = np.empty([2,2], dtype = int)
print(empty_array)

# O script acima retornará os seguintes valores aleatórios, ja que a matriz não foi inicializada:

[[   53902464    75528448]
 [          0 -2147483648]]


In [21]:
# criando uma matriz preenchida com zeros 

zeros_array = np.zeros([2,2], dtype = int)
print(zeros_array)

[[0 0]
 [0 0]]


In [23]:
# Nós podemos usar numpy.arange para criar uma matriz com valores uniformemente distribuídos dentro de um intervalo especificado. O construtor tem o seguinte formato:
# numpy.arange(start, stop, step, dtype)

my_array = np.arange(1,80)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79]


In [27]:
# para remodelar uma matriz (transforma-la em um vetor ou coloca-la em outro formato) podemos utilizar a função reshape

my_array = np.array(((6, 12, 93, 2),
                     (5, 26, 78, 90),
                     (3, 12, 16, 22),
                     (5, 3, 1, 16)))
 
my_array_reshaped = np.reshape(my_array, (8,2))

print (my_array_reshaped)

[[ 6 12]
 [93  2]
 [ 5 26]
 [78 90]
 [ 3 12]
 [16 22]
 [ 5  3]
 [ 1 16]]


In [28]:
#concatenando matrizes

array_1 = np.array(((1, 2),
                   (3, 4)))
 
array_2 = np.array(((5, 6),
                   (7, 8))) 
 
array_3 = np.array(((9, 10),
                   (11, 12))) 
 
contacted_array = np.concatenate((array_1, array_2, array_3))
 
print('First Array: ')
print(array_1)
print('Second Array: ')
print(array_2)
print('Third Array: ')
print(array_3)
print('Concatenated Array: ')
print(contacted_array)

First Array: 
[[1 2]
 [3 4]]
Second Array: 
[[5 6]
 [7 8]]
Third Array: 
[[ 9 10]
 [11 12]]
Concatenated Array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [29]:
# dividindo matrizes 

concatenated_array = np.array(((1, 2),
                       (3, 4),
                       (5, 6),
                       (7, 8),
                       (9, 10),
                       (11, 12)))
 
split_array = np.split(concatenated_array, 3)
 
print('Original Array:')
print(concatenated_array)
print('Split Sub-arrays:')
print('First Sub-array')
print(split_array[0])
print('Second Sub-array')
print(split_array[1])
print('Third Sub-array')
print(split_array[2])

Original Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Split Sub-arrays:
First Sub-array
[[1 2]
 [3 4]]
Second Sub-array
[[5 6]
 [7 8]]
Third Sub-array
[[ 9 10]
 [11 12]]
